pipeline {
    environment {
        CI = 'true'
    }
    stages {
        stage('Prepare environment') {
            checkout scm
            // Build the Docker image from the Dockerfile located at the root of the project
            docker.build('node1')
        }
        stage('install node modules...') {
            agent { docker 'node1' }
            steps {
                sh 'cd /path/to/package.json; yarn install'
            }
        }
        stage('Build') {
            steps {
            withDockerContainer(args: "-u root", image: "node1") {
                sh "npm install"
            }
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
